In [6]:
'''
Hello and Welcome to Kaggle, the online Data Science Community to learn, share, and compete. Most beginners get lost in the field, because they fall into the black box approach, using libraries and algorithms they don't understand. This tutorial will give you a 1-2-year head start over your peers, by providing a framework that teaches you how-to think like a input scientist vs what to think/code. Not only will you be able to submit your first competition, but you’ll be able to solve any problem thrown your way. I provide clear explanations, clean code, and plenty of links to resources. Please Note: This Kernel is still being improved. So check the Change Logs below for updates. Also, please be sure to upvote, fork, and comment and I'll continue to develop. Thanks, and may you have "statistically significant" luck!
'''
import sys
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import seaborn as sns
from pandas.plotting import scatter_matrix

# Configure Visualization Defaults
# %matplotlib inline = show plots in Jupyter Notebook browser
# %matplotlib inline
mpl.style.use('ggplot')
sns.set_style('white')
pylab.rcParams['figure.figsize'] = 12, 8
print('Python version:{}'.format(sys.version))
import pandas as pd

print("Pandas version:{}".format(pd.__version__))
import matplotlib

print('matplotlib.version {}'.format(matplotlib.__version__))

import numpy as np

print("Numpy version {}".format(np.__version__))

import scipy as sp

print("scipy version: {}".format(sp.__version__))

import IPython
from IPython import display

print("Ipython version :{} ".format(IPython.__version__))

import sklearn

print('Sklear version: {}'.format(sklearn.__version__))
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

import random
import time

import warnings

warnings.filterwarnings('ignore')
print('-' * 25)
from subprocess import check_output

# print(check_output(['ls', '../input/']).decode('utf8'))

import pandas as pd

data_raw = pd.read_csv('../input/playground-series-s4e6/train.csv')
data_val = pd.read_csv('../input/playground-series-s4e6/test.csv')
# #to play with our input we'll create a copy
# #remember python assignment or equal passes by reference vs values, so we use the copy function: https://stackoverflow.com/questions/46327494/python-pandas-dataframe-copydeep-false-vs-copydeep-true-vs
# data1 = data_raw.copy(deep=True)
# data_cleaner = [data1, data_val]
print("2" * 100)
print(data_raw.info())
print(data_raw.head())
print(data_raw.sample(9))
# Duplicates
import numpy as np

print("3" * 100)
print(
	f'Duplicates in train set :{data_raw.duplicated().sum()},'
	f'{np.round(100 * data_raw.duplicated().sum() / len(data_raw), 1)})')
print(
	f'Duplicates in test set :{data_raw.duplicated().sum()},'
	f'{np.round(100 * data_val.duplicated().sum() / len(data_raw), 1)})')

# print('Train columns with null value:\n', data1.isnull().sum())
# print("-" * 100)
# print('Test/Validation columns with null value :\n', data_val.isnull().sum())
# print("- " * 100)
print(data_raw.nunique())
print(data_raw.dtypes)
# Expenditure features
exp_feats = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
# Categorical feature
cat_feats = ['HomePlanet', 'CryoSleep', 'Destination', 'VIP']
# Qualitative features
qual_feats = ['PassengerId', 'Cabin', 'Name']
#
# for dataset in data_cleaner:
# 	dataset['Age_group'] = np.nan
# 	dataset.loc[dataset['Age'] <= 12, 'Age_group'] = 'Age_0-12'
# 	dataset.loc[(dataset['Age'] > 12) & (dataset['Age'] < 18), 'Age_group'] = 'Age_13-17'
# 	dataset.loc[(dataset['Age'] >= 18) & (dataset['Age'] <= 25), 'Age_group'] = 'Age_18-25'
# 	dataset.loc[(dataset['Age'] > 25) & (dataset['Age'] <= 30), 'Age_group'] = 'Age_26-30'
# 	dataset.loc[(dataset['Age'] > 30) & (dataset['Age'] <= 50), 'Age_group'] = 'Age_31-50'
# 	dataset.loc[dataset['Age'] > 50, 'Age_group'] = 'Age_51+'


# for dataset in data_cleaner:
# 	dataset['Group'] = dataset['PassengerId'].apply(lambda x: x.split('_')[0]).astype(int)
# 	dvc = dataset['Group'].value_counts()
# 	dataset['Group_size'] = dataset['Group'].map(lambda x: dvc[x])
# dataset['Solo'] = (dataset['Group_size'] == 1).astype(int)

## New features
# data_raw['Solo'] = (data_raw['Group_size'] == 1).astype(int)
# data_val['Solo'] = (data_val['Group_size'] == 1).astype(int)

# print('1' * 100)
# for dataset in data_cleaner:
# 	dataset['Solo'] = (dataset['Group_size'] == 1).astype(int)
#
## TODO 离散分批特征
# for dataset in data_cleaner:
# 	# New feature - training set
# 	dataset['Cabin_region1'] = (dataset['Cabin_number'] < 300).astype(int)
# 	dataset['Cabin_region2'] = ((dataset['Cabin_number'] >= 300) & (dataset['Cabin_number'] < 600)).astype(int)
# 	dataset['Cabin_region3'] = ((dataset['Cabin_number'] >= 600) & (dataset['Cabin_number'] < 900)).astype(int)
# 	dataset['Cabin_region4'] = ((dataset['Cabin_number'] >= 900) & (dataset['Cabin_number'] < 1200)).astype(int)
# 	dataset['Cabin_region5'] = ((dataset['Cabin_number'] >= 1200) & (dataset['Cabin_number'] < 1500)).astype(int)
# 	dataset['Cabin_region6'] = ((dataset['Cabin_number'] >= 1500) & (dataset['Cabin_number'] < 1500)).astype(int)
# 	dataset['Cabin_region7'] = (dataset['Cabin_number'] >= 1800).astype(int)

# plt.figure(figsize=(10, 4))
# TODO 求和特征
# data1['Cabin_region_plot'] = (
# 		data1['Cabin_region1'] + 2 * data1['Cabin_region2'] + 3 * data1['Cabin_region3'] + 4 * data1[
# 	'Cabin_region4'] + 5 * data1['Cabin_region5'] + 6 * data1['Cabin_region6'] + 7 * data1['Cabin_region7']).astype(int)
# sns.countplot(input=data1, x='Cabin_region_plot', hue='Transported')
# plt.title('Cabin region ')
# plt.show()
# data1.drop('Cabin_region_plot', axis=1, inplace=True)

print('1' * 100)  # TODO
##TODO 创造 新特征
# for data in data_cleaner:
# 	# Joint distribution of Surname and Cabin side
# 	SCS_gb = data[data['Group_size'] > 1].groupby(['Surname', 'Cabin_side'])['Cabin_side'].size().unstack().fillna(0)
# 	# Ratio of sides
# 	# TODO 特征比例
# 	SCS_gb['Ratio'] = SCS_gb['P'] / (SCS_gb['P'] + SCS_gb['S'])


# TODO One-hot encode cabin regions
# data['Cabin_region1'] = (data['Cabin_number'] < 300).astype(int)
# data['Cabin_region2'] = ((data['Cabin_number'] >= 300) & (data['Cabin_number'] < 600)).astype(int)
# data['Cabin_region3'] = ((data['Cabin_number'] >= 600) & (data['Cabin_number'] < 900)).astype(int)
# data['Cabin_region4'] = ((data['Cabin_number'] >= 900) & (data['Cabin_number'] < 1200)).astype(int)
# data['Cabin_region5'] = ((data['Cabin_number'] >= 1200) & (data['Cabin_number'] < 1500)).astype(int)
# data['Cabin_region6'] = ((data['Cabin_number'] >= 1500) & (data['Cabin_number'] < 1800)).astype(int)
# data['Cabin_region7'] = (data['Cabin_number'] >= 1800).astype(int)

print('2' * 100)
##TODO  特征分段
# for data in data_cleaner:
# 	data.loc[data['Age'] <= 12, 'Age_group'] = 'Age_0-12'
# 	data.loc[(data['Age'] > 12) & (data['Age'] < 18), 'Age_group'] = 'Age_13-17'
# 	data.loc[(data['Age'] >= 18) & (data['Age'] <= 25), 'Age_group'] = 'Age_18-25'
# 	data.loc[(data['Age'] > 25) & (data['Age'] <= 30), 'Age_group'] = 'Age_26-30'
# 	data.loc[(data['Age'] > 30) & (data['Age'] <= 50), 'Age_group'] = 'Age_31-50'
# 	data.loc[data['Age'] > 50, 'Agegroup'] = 'Age_51+'

##TODO log 特征
# for data in data_cleaner:
# 	data['Expenditure'] = data[exp_feats].sum(axis=1)
# 	data['No_spending'] = (data['Expenditure'] == 0).astype(int)
# 	# input.isna().sum()
# 	for col in ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Expenditure']:
# 		data[col] = np.log(1 + data[col])
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV, RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from xgboost import XGBClassifier


##Feature importance
def objective(trial):
	max_depth = trial.suggest_int('max_depth', 3, 10)
	n_estimators = trial.suggest_int('n_estimators', 100, 2000)
	gamma = trial.suggest_float('gamma', 0, 1)
	reg_alpha = trial.suggest_float('reg_alpha', 0, 2)
	reg_lambda = trial.suggest_float('reg_lambda', 0, 2)
	min_child_weight = trial.suggest_int('min_child_weight', 0, 10)
	subsample = trial.suggest_float('subsample', 0, 1)
	colsample_bytree = trial.suggest_float('colsample_bytree', 0, 1)
	learning_rate = trial.suggest_float('learning_rate', 0.01, 1)

	print('Training the model with', train.shape[1], 'features')

	params = {'n_estimators': n_estimators,
			  'learning_rate': learning_rate,
			  'gamma': gamma,
			  'reg_alpha': reg_alpha,
			  'reg_lambda': reg_lambda,
			  'max_depth': max_depth,
			  'min_child_weight': min_child_weight,
			  'subsample': subsample,
			  'colsample_bytree': colsample_bytree,
			  'eval_metric': 'logloss'}  # Using logloss for binary classification

	clf = XGBClassifier(**params,
						booster='gbtree',
						objective='binary:logistic',  # Binary classification objective
						verbosity=0)

	cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
	cv_results = cross_val_score(clf, train, data_val, cv=cv, scoring='roc_auc')  # Using roc_auc scoring

	validation_score = np.mean(cv_results)
	return validation_score


def reduce_mem_usage(df):
	""" iterate through all the columns of a dataframe and modify the data type
	    to reduce memory usage.
	"""
	start_mem = df.memory_usage().sum() / 1024 ** 2
	print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))
	for col in df.columns:
		col_type = df[col].dtype
		if col_type != object:
			c_min = df[col].min()
			c_max = df[col].max()
			if str(col_type)[:3] == 'int':
				if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
					df[col] = df[col].astype(np.int8)
				elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
					df[col] = df[col].astype(np.int16)
				elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
					df[col] = df[col].astype(np.int32)
				elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
					df[col] = df[col].astype(np.int64)
			else:
				if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
					df[col] = df[col].astype(np.float16)
				elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
					df[col] = df[col].astype(np.float32)
				else:
					df[col] = df[col].astype(np.float64)
		else:
			df[col] = df[col].astype('object')
	# df_v = df[col].value_counts()
	end_mem = df.memory_usage().sum() / 1024 ** 2
	print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))
	print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))
	return df


import re

train = data_raw.rename(columns=lambda x: re.sub('[^A-Za-z0-9_]+', '', x))
data_val = data_val.rename(columns=lambda x: re.sub('[^A-Za-z0-9_]+', '', x))

xgb_best_params_for_y1 = {'max_depth': 5, \
						  'n_estimators': 1627, \
						  'gamma': 0.8952807768735265,
						  'reg_alpha': 1.6314226873472901, \
						  'reg_lambda': 1.7229132141868826, \
						  'min_child_weight': 9,
						  'subsample': 0.9885054042421748, \
						  'colsample_bytree': 0.22439719563481197, \
						  'learning_rate': 0.10650804734533341}

train = reduce_mem_usage(train)
data_val = reduce_mem_usage(data_val)

data1_x_calc = ['Maritalstatus', 'Applicationmode', 'Applicationorder', 'Course',
				'Daytimeeveningattendance', 'Previousqualification',
				'Previousqualificationgrade', 'Nacionality', 'Mothersqualification',
				'Fathersqualification', 'Mothersoccupation', 'Fathersoccupation',
				'Admissiongrade', 'Displaced', 'Educationalspecialneeds', 'Debtor',
				'Tuitionfeesuptodate', 'Gender', 'Scholarshipholder', 'Ageatenrollment',
				'International', 'Curricularunits1stsemcredited',
				'Curricularunits1stsemenrolled', 'Curricularunits1stsemevaluations',
				'Curricularunits1stsemapproved', 'Curricularunits1stsemgrade',
				'Curricularunits1stsemwithoutevaluations',
				'Curricularunits2ndsemcredited', 'Curricularunits2ndsemenrolled',
				'Curricularunits2ndsemevaluations', 'Curricularunits2ndsemapproved',
				'Curricularunits2ndsemgrade', 'Curricularunits2ndsemwithoutevaluations',
				'Unemploymentrate', 'Inflationrate', 'GDP']
cur_sum = 'curr_sum'

cur_col = ['Curricularunits1stsemcredited',
		   'Curricularunits1stsemenrolled', 'Curricularunits1stsemevaluations',
		   'Curricularunits1stsemapproved', 'Curricularunits1stsemgrade',
		   'Curricularunits1stsemwithoutevaluations',
		   'Curricularunits2ndsemcredited', 'Curricularunits2ndsemenrolled',
		   'Curricularunits2ndsemevaluations', 'Curricularunits2ndsemapproved',
		   'Curricularunits2ndsemgrade', 'Curricularunits2ndsemwithoutevaluations',
		   ]
train[cur_sum] = train[cur_col].sum(axis=1)
data1_x_calc += [cur_sum]
Target = 'Target'
labelEncoder = LabelEncoder()
train[Target] = labelEncoder.fit_transform(train[Target])
import eli5
from eli5.sklearn import PermutationImportance
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

train_X, val_X, train_y, val_y = train_test_split(train[data1_x_calc], train[Target], random_state=1)

my_model = RandomForestClassifier(n_estimators=30, random_state=1,n_jobs=-1).fit(train[data1_x_calc], train[Target])
perms = PermutationImportance(my_model, random_state=1).fit(val_X, val_y)

Python version:3.8.0 (default, Nov  6 2019, 21:49:08)
[GCC 7.3.0]
Pandas version:2.0.3
matplotlib.version 3.7.5
Numpy version 1.24.3
scipy version: 1.10.1
Ipython version :8.12.3
Sklear version: 1.1.1
-------------------------
2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76518 entries, 0 to 76517
Data columns (total 38 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   id                                              76518 non-null  int64
 1   Marital status                                  76518 non-null  int64
 2   Application mode                                76518 non-null  int64
 3   Application order                               76518 non-null  int64
 4   Course                                          76518 non-null  int64
 5   Daytime/evening attendance                      76518 non-null  int64
 6   Previous qualification                          76518 non-null  int64
 7   Previous qualification (grade)                  76518 non-null  float64
 8   Nacionality                                     76518 non-null  int64
 9   Mother's qualification                          76518 non-null  int64
 10  Father's qualification                          76518 non-null  int64
 11  Mother's occupation                             76518 non-null  int64
 12  Father's occupation                             76518 non-null  int64
 13  Admission grade                                 76518 non-null  float64
 14  Displaced                                       76518 non-null  int64
 15  Educational special needs                       76518 non-null  int64
 16  Debtor                                          76518 non-null  int64
 17  Tuition fees up to date                         76518 non-null  int64
 18  Gender                                          76518 non-null  int64
 19  Scholarship holder                              76518 non-null  int64
 20  Age at enrollment                               76518 non-null  int64
 21  International                                   76518 non-null  int64
 22  Curricular units 1st sem (credited)             76518 non-null  int64
 23  Curricular units 1st sem (enrolled)             76518 non-null  int64
 24  Curricular units 1st sem (evaluations)          76518 non-null  int64
 25  Curricular units 1st sem (approved)             76518 non-null  int64
 26  Curricular units 1st sem (grade)                76518 non-null  float64
 27  Curricular units 1st sem (without evaluations)  76518 non-null  int64
 28  Curricular units 2nd sem (credited)             76518 non-null  int64
 29  Curricular units 2nd sem (enrolled)             76518 non-null  int64
 30  Curricular units 2nd sem (evaluations)          76518 non-null  int64
 31  Curricular units 2nd sem (approved)             76518 non-null  int64
 32  Curricular units 2nd sem (grade)                76518 non-null  float64
 33  Curricular units 2nd sem (without evaluations)  76518 non-null  int64
 34  Unemployment rate                               76518 non-null  float64
 35  Inflation rate                                  76518 non-null  float64
 36  GDP                                             76518 non-null  float64
 37  Target                                          76518 non-null  object
dtypes: float64(7), int64(30), object(1)
memory usage: 22.2+ MB
None
   id  Marital status  Application mode  Application order  Course  \
0   0               1                 1                  1    9238
1   1               1                17                  1    9238
2   2               1                17                  2    9254
3   3               1                 1                  3    9500
4   4               1                 1                  2    9500

   Daytime/evening attendance  Previous qualification  \
0                           1                       1
1                           1                       1
2                           1                       1
3                           1                       1
4                           1                       1

   Previous qualification (grade)  Nacionality  Mother's qualification  ...  \
0                           126.0            1                       1  ...
1                           125.0            1                      19  ...
2                           137.0            1                       3  ...
3                           131.0            1                      19  ...
4                           132.0            1                      19  ...

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    6
1                                    0                                    6
2                                    0                                    6
3                                    0                                    8
4                                    0                                    7

   Curricular units 2nd sem (evaluations)  \
0                                       7
1                                       9
2                                       0
3                                      11
4                                      12

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    6                         12.428571
1                                    0                          0.000000
2                                    0                          0.000000
3                                    7                         12.820000
4                                    6                         12.933333

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               11.1
1                                               0               11.1
2                                               0               16.2
3                                               0               11.1
4                                               0                7.6

   Inflation rate   GDP    Target
0             0.6  2.02  Graduate
1             0.6  2.02   Dropout
2             0.3 -0.92   Dropout
3             0.6  2.02  Enrolled
4             2.6  0.32  Graduate

[5 rows x 38 columns]
          id  Marital status  Application mode  Application order  Course  \
5799    5799               1                44                  1    9003
43332  43332               2                39                  1    9500
53013  53013               1                 1                  1    9254
39105  39105               2                39                  1    9991
53453  53453               1                43                  1    9147
47156  47156               4                39                  1    9991
5624    5624               1                 1                  1    9130
8030    8030               1                39                  1    9254
71152  71152               1                 1                  1    9119

       Daytime/evening attendance  Previous qualification  \
5799                            1                      39
43332                           1                       1
53013                           1                       1
39105                           0                      19
53453                           1                       1
47156                           0                      19
5624                            1                       1
8030                            1                       1
71152                           1                       1

       Previous qualification (grade)  Nacionality  Mother's qualification  \
5799                            130.0            1                       1
43332                           133.1            1                      37
53013                           148.0            1                       3
39105                           133.1            1                      37
53453                           135.0            1                      37
47156                           133.1            1                      37
5624                            131.0            1                       3
8030                            133.1            1                       1
71152                           108.0           41                       1

       ...  Curricular units 2nd sem (credited)  \
5799   ...                                    0
43332  ...                                    0
53013  ...                                    0
39105  ...                                    0
53453  ...                                    0
47156  ...                                    0
5624   ...                                    0
8030   ...                                    0
71152  ...                                    0

       Curricular units 2nd sem (enrolled)  \
5799                                     6
43332                                    8
53013                                    6
39105                                    5
53453                                    5
47156                                    5
5624                                     5
8030                                     6
71152                                    5

       Curricular units 2nd sem (evaluations)  \
5799                                        6
43332                                      12
53013                                      13
39105                                       5
53453                                       8
47156                                       5
5624                                       10
8030                                        7
71152                                       5

       Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
5799                                     0                          0.000000
43332                                    7                         13.016667
53013                                    3                         10.000000
39105                                    0                          0.000000
53453                                    3                         12.000000
47156                                    0                          0.000000
5624                                     4                         11.800000
8030                                     5                         11.600000
71152                                    0                          0.000000

       Curricular units 2nd sem (without evaluations)  Unemployment rate  \
5799                                                0                8.9
43332                                               0               11.1
53013                                               0               10.8
39105                                               0                9.4
53453                                               0                7.6
47156                                               0                7.6
5624                                                0               11.1
8030                                                0               12.7
71152                                               0                8.9

       Inflation rate   GDP    Target
5799              1.4  3.51   Dropout
43332             0.6  2.02  Graduate
53013             1.4  1.74  Enrolled
39105            -0.8 -3.12   Dropout
53453             2.6  0.32  Graduate
47156             2.6  0.32   Dropout
5624              0.6  2.02   Dropout
8030              3.7 -1.70  Enrolled
71152             1.4  3.51   Dropout

[9 rows x 38 columns]
3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333
Duplicates in train set :0,0.0)
Duplicates in test set :0,0.0)
id                                                76518
Marital status                                        6
Application mode                                     22
Application order                                     8
Course                                               19
Daytime/evening attendance                            2
Previous qualification                               21
Previous qualification (grade)                      110
Nacionality                                          18
Mother's qualification                               35
Father's qualification                               39
Mother's occupation                                  40
Father's occupation                                  56
Admission grade                                     668
Displaced                                             2
Educational special needs                             2
Debtor                                                2
Tuition fees up to date                               2
Gender                                                2
Scholarship holder                                    2
Age at enrollment                                    46
International                                         2
Curricular units 1st sem (credited)                  21
Curricular units 1st sem (enrolled)                  24
Curricular units 1st sem (evaluations)               36
Curricular units 1st sem (approved)                  23
Curricular units 1st sem (grade)                   1206
Curricular units 1st sem (without evaluations)       12
Curricular units 2nd sem (credited)                  20
Curricular units 2nd sem (enrolled)                  22
Curricular units 2nd sem (evaluations)               31
Curricular units 2nd sem (approved)                  21
Curricular units 2nd sem (grade)                   1234
Curricular units 2nd sem (without evaluations)       11
Unemployment rate                                    11
Inflation rate                                       13
GDP                                                  11
Target                                                3
dtype: int64
id                                                  int64
Marital status                                      int64
Application mode                                    int64
Application order                                   int64
Course                                              int64
Daytime/evening attendance                          int64
Previous qualification                              int64
Previous qualification (grade)                    float64
Nacionality                                         int64
Mother's qualification                              int64
Father's qualification                              int64
Mother's occupation                                 int64
Father's occupation                                 int64
Admission grade                                   float64
Displaced                                           int64
Educational special needs                           int64
Debtor                                              int64
Tuition fees up to date                             int64
Gender                                              int64
Scholarship holder                                  int64
Age at enrollment                                   int64
International                                       int64
Curricular units 1st sem (credited)                 int64
Curricular units 1st sem (enrolled)                 int64
Curricular units 1st sem (evaluations)              int64
Curricular units 1st sem (approved)                 int64
Curricular units 1st sem (grade)                  float64
Curricular units 1st sem (without evaluations)      int64
Curricular units 2nd sem (credited)                 int64
Curricular units 2nd sem (enrolled)                 int64
Curricular units 2nd sem (evaluations)              int64
Curricular units 2nd sem (approved)                 int64
Curricular units 2nd sem (grade)                  float64
Curricular units 2nd sem (without evaluations)      int64
Unemployment rate                                 float64
Inflation rate                                    float64
GDP                                               float64
Target                                             object
dtype: object
1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
Memory usage of dataframe is 22.18 MB
Memory usage after optimization is: 4.23 MB
Decreased by 80.9%
Memory usage of dataframe is 14.40 MB
Memory usage after optimization is: 2.43 MB
Decreased by 83.1%

In [10]:
eli5.show_weights(perms, feature_names=val_X.columns.tolist())

In [12]:

print('4'*100)
eli5.show_weights(my_model)

4444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444

In [13]:

print(perms.feature_importances_)
print(perms.feature_importances_std_)

[6.27286984e-04 1.91531626e-02 7.92472556e-03 2.53110298e-02
 3.13643492e-04 1.85049660e-03 2.27182436e-02 2.50914794e-04
 1.35703084e-02 1.00679561e-02 1.22216414e-02 1.33612128e-02
 2.82383691e-02 4.46419237e-03 3.76372190e-04 5.50967067e-03
 4.75797177e-02 1.50653424e-02 3.90067956e-02 2.28750653e-02
 1.15002614e-04 1.07684266e-03 1.23261892e-02 3.42289597e-02
 8.19550444e-02 4.87924726e-02 9.30475693e-04 8.25927862e-04
 9.53476215e-03 4.48823837e-02 2.27192891e-01 7.33403032e-02
 4.28646106e-04 1.15525353e-02 9.75431260e-03 1.15211709e-02
 4.07736539e-02]
[4.67552112e-05 9.99840269e-04 3.44532296e-04 6.22388963e-04
 5.72632052e-05 1.53653303e-04 6.36455045e-04 2.09095661e-05
 3.74917325e-04 6.18159770e-04 7.23875771e-04 2.69806334e-04
 6.52398568e-04 2.48727177e-04 2.09095661e-05 2.30479955e-04
 6.26764027e-04 5.07245561e-04 3.29615949e-04 4.51617586e-04
 2.09095661e-05 5.33091428e-05 2.07521518e-04 6.66487295e-04
 8.13460059e-04 3.87814678e-04 3.91182163e-05 5.12177678e-05
 2.79750929e-04 8.99111343e-04 4.27719473e-03 6.25542093e-04
 3.91182163e-05 5.47255717e-04 4.26729360e-04 3.38127792e-04
 5.84907506e-04]